[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_REST_API_ENDPOINT = "/api"
  NODE_VERSION = "22"
  NETLIFY_NEXT_PLUGIN_VERSION = "4"

[[plugins]]
  package = "@netlify/plugin-nextjs"
